# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    config.yaml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42tokyo.jp>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/13 20:15:24 by user42            #+#    #+#              #
#    Updated: 2021/03/18 12:22:05 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: ft-secret
type: Opaque
stringData:
  mysql_root_password: rootpass
  db_name: wordpress
  db_user: wp_user
  db_pass: userpass
  db_host: localhost
  wp_admin: admin
  wp_adminpass: password
  wp_adminmail: admin@example.com

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
