# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tkomatsu <tkomatsu@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/24 18:47:59 by tkomatsu          #+#    #+#              #
#    Updated: 2021/03/24 18:48:00 by tkomatsu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: tkomatsu/grafana:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep telegraf && pgrep grafana-server"]
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: influxdb-storage
          mountPath: var/lib/grafana
        env:
        - name: SERVICE
          value: grafana
        - name: USER
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: influxdb_name
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: influxdb_password
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
