# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb-configmap.yaml                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tkomatsu <tkomatsu@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/24 18:44:21 by tkomatsu          #+#    #+#              #
#    Updated: 2021/03/24 18:44:22 by tkomatsu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.49.50-192.168.49.50
